### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by revilationer** [pinetum/AirUnlock-for-Android#10]
Hey, i just saw your app and if you need a new logo i can help you.. I ll be waiting for your reply

**Comment by pinetum** [comment]
Yes!!  Can you make a pull request ?

Helped me a great favor!

**Comment by revilationer** [comment]
I am going to prepare a logo and i will share with you on this issue, if you like it i will make a PR

**Comment by pinetum** [comment]
Thank you!

**Comment by revilationer** [comment]
Hi @pinetum !
I've prepared a design for you, that is demo version. 
I can edit the things that you want to change, help me for a better design :)
I will serve the logo with 6 different colors, B&W version and logomark versions.
I'm waiting for your reply for next stage.
![image](https://user-images.githubusercontent.com/35149966/39082241-7f4eda98-4558-11e8-9a9e-81cb9e7e3f0b.png)

**Comment by wad3g** [comment]
I know I'm not apart of this discussion, but thought I'd throw an idea out there to see what you (y'all) thought.

What's if you killed the monitor and instead had a finger print in the shape of a keyhole?

Just my two cents. Carry on.

**Comment by pinetum** [comment]
@wad3g It's a good idea.

@revilationer  Can you try it ?

**Comment by revilationer** [comment]
Hi, 
@wad3g Thank you for your feedback:)
I've tried to do something that you explained.
@pinetum I hope you will like it.
![image](https://user-images.githubusercontent.com/35149966/39114233-e3cd2846-46e6-11e8-8e18-120a551c4de5.png)

**Comment by revilationer** [comment]
Hi @pinetum, i am waiting for your feedback to make a PR.

**Comment by pinetum** [comment]
@revilationer
Looks good!
Thank you, can you make a PR?

**Comment by revilationer** [comment]
@pinetum 
Thank you for merge!
You can find out all project files from [here](https://drive.google.com/drive/folders/1BiRsRlXlSmye2n-QmUGzBqyDSt8BjIeI).
